# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f97c904917899152a0619c077846986faccb1ef9e8c2716f2e363791cd9a4ab3e0cc05d11ad0437d97c392ff8686ab757ee978df0da329cd67722b434a97c6b

test:
  secret_key_base: f3a8845f798d8fb556c0d38e9d781ed3846e2324757d944911ac2b5d03c4358a661969cad3c2a119b117f25b4c0c5e5facc1101c5bda8e6ab90fe0d6a28c6265

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
